name: edit-flows
channels:
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - asttokens==3.0.0=py310h06a4308_0
  - ncurses==6.4=h6a678d5_0
  - pure_eval==0.2.2=pyhd3eb1b0_0
  - pyzmq==26.2.0=py310h6a678d5_0
  - ipython==8.30.0=py310h06a4308_0
  - pygments==2.19.1=py310h06a4308_0
  - python-dateutil==2.9.0post0=py310h06a4308_2
  - wcwidth==0.2.5=pyhd3eb1b0_0
  - xz==5.6.4=h5eee18b_1
  - jupyter_core==5.7.2=py310h06a4308_0
  - libgcc-ng==11.2.0=h1234567_1
  - ptyprocess==0.7.0=pyhd3eb1b0_2
  - tk==8.6.14=h39e8969_0
  - _libgcc_mutex==0.1=main
  - sqlite==3.45.3=h5eee18b_0
  - pexpect==4.9.0=py310h06a4308_0
  - parso==0.8.4=py310h06a4308_0
  - stack_data==0.2.0=pyhd3eb1b0_0
  - libgomp==11.2.0=h1234567_1
  - readline==8.2=h5eee18b_0
  - prompt-toolkit==3.0.43=py310h06a4308_0
  - six==1.17.0=py310h06a4308_0
  - python==3.10.16=he870216_1
  - jupyter_client==8.6.3=py310h06a4308_0
  - jedi==0.19.2=py310h06a4308_0
  - setuptools==78.1.1=py310h06a4308_0
  - packaging==24.2=py310h06a4308_0
  - decorator==5.1.1=pyhd3eb1b0_0
  - ld_impl_linux-64==2.40=h12ee557_0
  - wheel==0.45.1=py310h06a4308_0
  - debugpy==1.8.11=py310h6a678d5_0
  - tzdata==2025b=h04d1e81_0
  - executing==0.8.3=pyhd3eb1b0_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - openssl==3.0.16=h5eee18b_0
  - bzip2==1.0.8=h5eee18b_6
  - ipykernel==6.29.5=py310h06a4308_1
  - _openmp_mutex==5.1=1_gnu
  - prompt_toolkit==3.0.43=hd3eb1b0_0
  - ca-certificates==2025.2.25=h06a4308_0
  - traitlets==5.14.3=py310h06a4308_0
  - tornado==6.4.2=py310h5eee18b_0
  - nest-asyncio==1.6.0=py310h06a4308_0
  - zlib==1.2.13=h5eee18b_1
  - comm==0.2.1=py310h06a4308_0
  - matplotlib-inline==0.1.6=py310h06a4308_0
  - libffi==3.4.4=h6a678d5_1
  - platformdirs==4.3.7=py310h06a4308_0
  - libuuid==1.41.5=h5eee18b_0
  - libsodium==1.0.18=h7b6447c_0
  - pip==25.1=pyhc872135_2
  - zeromq==4.3.5=h6a678d5_0
prefix: /venv/goedelv2
